version: "3.8"

services:
  alarm_videoreg:
    container_name: alarm_videoreg
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    env_file: .env

